#!/bin/bash
 
NAME="dcmdb"                                  # Name of the application
DJANGODIR=/srv/www/dcmdb            		  # Django project directory
SOCKFILE=/srv/www/dcmdb/run/gunicorn.sock  	  # we will communicte using this unix socket
USER=ubuntu                                   # the user to run as
GROUP=ubuntu                                  # the group to run as
NUM_WORKERS=3                                 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=dicomdb.settings       # which settings file should Django use
DJANGO_WSGI_MODULE=dicomdb.wsgi               # WSGI module name
VIRTENV=/srv/www/dcmdb_virt					  # Virtual environment dir
 
echo "Starting $NAME"
 
# Activate the virtual environment
cd $VIRTENV
source ./bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# MOUNT EBS: sudo mount /dev/xvdf /mnt/media
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
cd $DJANGODIR
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE
